FROM 553308542477.dkr.ecr.us-east-1.amazonaws.com/dockerproductionawsaravind/microtrader-base:latest
MAINTAINER Aravind Kumar Sunkari <aravindkumar.sunkari.vcs@gmail.com>
LABEL application.component=microtrader-portfolio

# Copy application artefacts
ARG app_version
LABEL application.version=${app_version}
COPY build/jars/microtrader-portfolio-${app_version}-fat.jar /app/app.jar